/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tekkom;

import tekkom.huffman.huffmantree;
import tekkom.huffman.huffmannode;
import tekkom.huffman.huffmanleaf;
import java.awt.Color;
import javax.swing.JPanel;
import com.sun.org.apache.xml.internal.security.utils.XMLUtils;
import java.util.PriorityQueue;
import tekkom.shano.counter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.StringTokenizer;
/**
 *
 * @author ini nopal
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setColor(btn_1); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4,btn_5,btn_6}, new JPanel[]{ind_2,ind_3,ind_4,ind_5,ind_6});
        //jProgressBar1.setValue(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utama = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        sider = new javax.swing.JPanel();
        btn_1 = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_2 = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_3 = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_4 = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_5 = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_6 = new javax.swing.JPanel();
        ind_6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        huffman = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inp_huffman = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        out_huffman = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        clear_huffman = new java.awt.Button();
        btn_huffman = new java.awt.Button();
        rle = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inp_rle = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        out_rle = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        btn_rle = new java.awt.Button();
        jLabel25 = new javax.swing.JLabel();
        clear_rle = new java.awt.Button();
        dicti = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        inp_dicti = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        out_dicti = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btn_dicti = new java.awt.Button();
        jLabel18 = new javax.swing.JLabel();
        clear_dicti = new java.awt.Button();
        shano = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        inp_shano = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        out_shano = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        btn_shano = new java.awt.Button();
        jLabel22 = new javax.swing.JLabel();
        clear_shano = new java.awt.Button();
        bwt = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        inp_bwt = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        out_bwt = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        btn_bwt = new java.awt.Button();
        jLabel28 = new javax.swing.JLabel();
        clear_bwt = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        utama.setBackground(new java.awt.Color(34, 55, 82));
        utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(23, 34, 54));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("KOMPRESI");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TEKNIK");

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("x");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 699, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        utama.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 80));

        sider.setBackground(new java.awt.Color(23, 34, 54));
        sider.setDoubleBuffered(false);

        btn_1.setBackground(new java.awt.Color(23, 35, 51));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home");

        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
        btn_1.setLayout(btn_1Layout);
        btn_1Layout.setHorizontalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_1Layout.setVerticalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_2.setBackground(new java.awt.Color(23, 35, 51));
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_2MousePressed(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Huffman");

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
        btn_2.setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_2Layout.setVerticalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_3.setBackground(new java.awt.Color(23, 35, 51));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Run Length");

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
        btn_3.setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        btn_3Layout.setVerticalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_4.setBackground(new java.awt.Color(23, 35, 51));
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_4MousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dictionary");

        javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn_4);
        btn_4.setLayout(btn_4Layout);
        btn_4Layout.setHorizontalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 112, Short.MAX_VALUE))
        );
        btn_4Layout.setVerticalGroup(
            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_4Layout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_5.setBackground(new java.awt.Color(23, 35, 51));
        btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_5MousePressed(evt);
            }
        });

        ind_5.setOpaque(false);
        ind_5.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Shannonfano");

        javax.swing.GroupLayout btn_5Layout = new javax.swing.GroupLayout(btn_5);
        btn_5.setLayout(btn_5Layout);
        btn_5Layout.setHorizontalGroup(
            btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_5Layout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addGap(0, 95, Short.MAX_VALUE))
        );
        btn_5Layout.setVerticalGroup(
            btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_5Layout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_6.setBackground(new java.awt.Color(23, 35, 51));
        btn_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_6MousePressed(evt);
            }
        });

        ind_6.setOpaque(false);
        ind_6.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_6Layout = new javax.swing.GroupLayout(ind_6);
        ind_6.setLayout(ind_6Layout);
        ind_6Layout.setHorizontalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_6Layout.setVerticalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("BWT");

        javax.swing.GroupLayout btn_6Layout = new javax.swing.GroupLayout(btn_6);
        btn_6.setLayout(btn_6Layout);
        btn_6Layout.setHorizontalGroup(
            btn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_6Layout.createSequentialGroup()
                .addComponent(ind_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel13)
                .addGap(0, 141, Short.MAX_VALUE))
        );
        btn_6Layout.setVerticalGroup(
            btn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_6Layout.createSequentialGroup()
                .addComponent(ind_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout siderLayout = new javax.swing.GroupLayout(sider);
        sider.setLayout(siderLayout);
        siderLayout.setHorizontalGroup(
            siderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(siderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        siderLayout.setVerticalGroup(
            siderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siderLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        utama.add(sider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 580));

        main.setBackground(new java.awt.Color(34, 55, 82));
        main.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(34, 55, 82));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 148, 20));
        jLabel1.setText("KOMPRESI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 148, 20));
        jLabel2.setText("TEKNIK");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAUFAL RIZQI ARRAFI");

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("201851262");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homeLayout.createSequentialGroup()
                    .addGap(158, 158, 158)
                    .addComponent(jLabel2)
                    .addContainerGap(432, Short.MAX_VALUE)))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homeLayout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(jLabel2)
                    .addContainerGap(316, Short.MAX_VALUE)))
        );

        main.add(home, "card2");

        huffman.setBackground(new java.awt.Color(34, 55, 82));

        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Hasil Kompresi");

        inp_huffman.setColumns(20);
        inp_huffman.setRows(5);
        jScrollPane1.setViewportView(inp_huffman);

        out_huffman.setColumns(20);
        out_huffman.setRows(5);
        jScrollPane2.setViewportView(out_huffman);

        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("Masukkan Teks");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(45, 172, 253));
        jLabel17.setText("METODE HUFFMAN");

        clear_huffman.setBackground(new java.awt.Color(255, 102, 102));
        clear_huffman.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clear_huffman.setForeground(new java.awt.Color(255, 255, 255));
        clear_huffman.setLabel("Clear");
        clear_huffman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_huffmanActionPerformed(evt);
            }
        });

        btn_huffman.setBackground(new java.awt.Color(71, 120, 197));
        btn_huffman.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_huffman.setForeground(new java.awt.Color(255, 255, 255));
        btn_huffman.setLabel("Proses");
        btn_huffman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huffmanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout huffmanLayout = new javax.swing.GroupLayout(huffman);
        huffman.setLayout(huffmanLayout);
        huffmanLayout.setHorizontalGroup(
            huffmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(huffmanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(huffmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(huffmanLayout.createSequentialGroup()
                        .addGroup(huffmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(huffmanLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(huffmanLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clear_huffman, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, huffmanLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(212, 212, 212))
            .addGroup(huffmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, huffmanLayout.createSequentialGroup()
                    .addContainerGap(286, Short.MAX_VALUE)
                    .addComponent(btn_huffman, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(276, 276, 276)))
        );
        huffmanLayout.setVerticalGroup(
            huffmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, huffmanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(huffmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(huffmanLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3))
                    .addComponent(clear_huffman, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(huffmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, huffmanLayout.createSequentialGroup()
                    .addContainerGap(260, Short.MAX_VALUE)
                    .addComponent(btn_huffman, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(199, 199, 199)))
        );

        main.add(huffman, "card3");

        rle.setBackground(new java.awt.Color(34, 55, 82));

        jLabel23.setForeground(new java.awt.Color(255, 204, 204));
        jLabel23.setText("Hasil Kompresi");

        inp_rle.setColumns(20);
        inp_rle.setRows(5);
        jScrollPane3.setViewportView(inp_rle);

        out_rle.setColumns(20);
        out_rle.setRows(5);
        jScrollPane4.setViewportView(out_rle);

        jLabel24.setForeground(new java.awt.Color(255, 204, 204));
        jLabel24.setText("Masukkan Teks");

        btn_rle.setBackground(new java.awt.Color(71, 120, 197));
        btn_rle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_rle.setForeground(new java.awt.Color(255, 255, 255));
        btn_rle.setLabel("Proses");
        btn_rle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rleActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(45, 172, 253));
        jLabel25.setText("METODE RUN LENGTH CODING");

        clear_rle.setBackground(new java.awt.Color(255, 102, 102));
        clear_rle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clear_rle.setForeground(new java.awt.Color(255, 255, 255));
        clear_rle.setLabel("Clear");
        clear_rle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_rleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rleLayout = new javax.swing.GroupLayout(rle);
        rle.setLayout(rleLayout);
        rleLayout.setHorizontalGroup(
            rleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(rleLayout.createSequentialGroup()
                        .addGroup(rleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(177, 177, 177)
                        .addComponent(btn_rle, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear_rle, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(112, 112, 112))
        );
        rleLayout.setVerticalGroup(
            rleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rleLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rleLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel23))
                    .addComponent(btn_rle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_rle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        main.add(rle, "card3");

        dicti.setBackground(new java.awt.Color(34, 55, 82));

        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("Hasil Kompresi");

        inp_dicti.setColumns(20);
        inp_dicti.setRows(5);
        jScrollPane5.setViewportView(inp_dicti);

        out_dicti.setColumns(20);
        out_dicti.setRows(5);
        jScrollPane6.setViewportView(out_dicti);

        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("Masukkan Teks");

        btn_dicti.setBackground(new java.awt.Color(71, 120, 197));
        btn_dicti.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_dicti.setForeground(new java.awt.Color(255, 255, 255));
        btn_dicti.setLabel("Proses");
        btn_dicti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dictiActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(45, 172, 253));
        jLabel18.setText("METODE LEMPEL ZIV WELCH ");

        clear_dicti.setBackground(new java.awt.Color(255, 102, 102));
        clear_dicti.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clear_dicti.setForeground(new java.awt.Color(255, 255, 255));
        clear_dicti.setLabel("Clear");
        clear_dicti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_dictiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dictiLayout = new javax.swing.GroupLayout(dicti);
        dicti.setLayout(dictiLayout);
        dictiLayout.setHorizontalGroup(
            dictiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dictiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dictiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(dictiLayout.createSequentialGroup()
                        .addGroup(dictiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(177, 177, 177)
                        .addComponent(btn_dicti, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear_dicti, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dictiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(142, 142, 142))
        );
        dictiLayout.setVerticalGroup(
            dictiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dictiLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dictiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dictiLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5))
                    .addComponent(btn_dicti, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_dicti, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        main.add(dicti, "card3");

        shano.setBackground(new java.awt.Color(34, 55, 82));

        jLabel20.setForeground(new java.awt.Color(255, 204, 204));
        jLabel20.setText("Hasil Kompresi");

        inp_shano.setColumns(20);
        inp_shano.setRows(5);
        jScrollPane7.setViewportView(inp_shano);

        out_shano.setColumns(20);
        out_shano.setRows(5);
        jScrollPane8.setViewportView(out_shano);

        jLabel21.setForeground(new java.awt.Color(255, 204, 204));
        jLabel21.setText("Masukkan Teks");

        btn_shano.setBackground(new java.awt.Color(71, 120, 197));
        btn_shano.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_shano.setForeground(new java.awt.Color(255, 255, 255));
        btn_shano.setLabel("Proses");
        btn_shano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shanoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(45, 172, 253));
        jLabel22.setText("METODE SHANOFANNO");

        clear_shano.setBackground(new java.awt.Color(255, 102, 102));
        clear_shano.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clear_shano.setForeground(new java.awt.Color(255, 255, 255));
        clear_shano.setLabel("Clear");
        clear_shano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_shanoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shanoLayout = new javax.swing.GroupLayout(shano);
        shano.setLayout(shanoLayout);
        shanoLayout.setHorizontalGroup(
            shanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shanoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(shanoLayout.createSequentialGroup()
                        .addGroup(shanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(177, 177, 177)
                        .addComponent(btn_shano, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear_shano, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane8))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shanoLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(212, 212, 212))
        );
        shanoLayout.setVerticalGroup(
            shanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shanoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(shanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shanoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel20))
                    .addComponent(btn_shano, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_shano, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        main.add(shano, "card4");

        bwt.setBackground(new java.awt.Color(34, 55, 82));

        jLabel26.setForeground(new java.awt.Color(255, 204, 204));
        jLabel26.setText("Hasil Kompresi");

        inp_bwt.setColumns(20);
        inp_bwt.setRows(5);
        jScrollPane9.setViewportView(inp_bwt);

        out_bwt.setColumns(20);
        out_bwt.setRows(5);
        jScrollPane10.setViewportView(out_bwt);

        jLabel27.setForeground(new java.awt.Color(255, 204, 204));
        jLabel27.setText("Masukkan Teks");

        btn_bwt.setBackground(new java.awt.Color(71, 120, 197));
        btn_bwt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_bwt.setForeground(new java.awt.Color(255, 255, 255));
        btn_bwt.setLabel("Proses");
        btn_bwt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bwtActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(45, 172, 253));
        jLabel28.setText("METODE BURROWS WHEELER TRANSFORM");

        clear_bwt.setBackground(new java.awt.Color(255, 102, 102));
        clear_bwt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clear_bwt.setForeground(new java.awt.Color(255, 255, 255));
        clear_bwt.setLabel("Clear");
        clear_bwt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_bwtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bwtLayout = new javax.swing.GroupLayout(bwt);
        bwt.setLayout(bwtLayout);
        bwtLayout.setHorizontalGroup(
            bwtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bwtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bwtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addGroup(bwtLayout.createSequentialGroup()
                        .addGroup(bwtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(177, 177, 177)
                        .addComponent(btn_bwt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear_bwt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane10))
                .addContainerGap())
            .addGroup(bwtLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel28)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        bwtLayout.setVerticalGroup(
            bwtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bwtLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bwtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bwtLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel26))
                    .addComponent(btn_bwt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_bwt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        main.add(bwt, "card4");

        utama.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 710, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        // TODO add your handling code here:
        setColor(btn_1);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btn_2,btn_3,btn_4,btn_5,btn_6}, new JPanel[]{ind_2,ind_3,ind_4,ind_5,ind_6});
        
        // remove panel
        main.removeAll();
        main.repaint();
        main.revalidate();

        // add panel
        main.add(home);
        main.repaint();
        main.revalidate();

    }//GEN-LAST:event_btn_1MousePressed

    private void btn_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MousePressed
        // TODO add your handling code here:
        setColor(btn_5);
        ind_5.setOpaque(true);
        resetColor(new JPanel[]{btn_1,btn_2,btn_3,btn_4,btn_6}, new JPanel[]{ind_1,ind_2,ind_3,ind_4,ind_6});
        
        // remove panel
        main.removeAll();
        main.repaint();
        main.revalidate();

        // add panel
        main.add(shano);
        main.repaint();
        main.revalidate();
        
    }//GEN-LAST:event_btn_5MousePressed

    private void btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MousePressed
        // TODO add your handling code here:
        setColor(btn_2);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btn_1,btn_3,btn_4,btn_5,btn_6}, new JPanel[]{ind_1,ind_3,ind_4,ind_5,ind_6});
        
        // remove panel
        main.removeAll();
        main.repaint();
        main.revalidate();

        // add panel
        main.add(huffman);
        main.repaint();
        main.revalidate();
        
    }//GEN-LAST:event_btn_2MousePressed

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
        // TODO add your handling code here:
        setColor(btn_3);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btn_1,btn_2,btn_4,btn_5,btn_6}, new JPanel[]{ind_1,ind_2,ind_4,ind_5,ind_6});
        
        // remove panel
        main.removeAll();
        main.repaint();
        main.revalidate();

        // add panel
        main.add(rle);
        main.repaint();
        main.revalidate();
        
    }//GEN-LAST:event_btn_3MousePressed

    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MousePressed
        // TODO add your handling code here:
        setColor(btn_4);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btn_1,btn_2,btn_3,btn_5,btn_6}, new JPanel[]{ind_1,ind_2,ind_3,ind_5,ind_6});
        
        // remove panel
        main.removeAll();
        main.repaint();
        main.revalidate();

        // add panel
        main.add(dicti);
        main.repaint();
        main.revalidate();
        
    }//GEN-LAST:event_btn_4MousePressed

    private void btn_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MousePressed
        // TODO add your handling code here:
        setColor(btn_6);
        ind_6.setOpaque(true);
        resetColor(new JPanel[]{btn_1,btn_2,btn_3,btn_4,btn_5}, new JPanel[]{ind_1,ind_2,ind_3,ind_4,ind_5});
        
        // remove panel
        main.removeAll();
        main.repaint();
        main.revalidate();

        // add panel
        main.add(bwt);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_btn_6MousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    //METODE HUFFMAN
    
    public huffmantree builTree(int[] charFreqs){
        PriorityQueue<huffmantree> tree = new PriorityQueue<huffmantree>();
        
        
        for(int i = 0; i < charFreqs.length; i++){
            if(charFreqs[i] > 0){
                tree.offer(new huffmanleaf(charFreqs[i], (char) i));
            }
        }
        
        assert tree.size() > 0;
        
        while (tree.size() > 1) {            
            huffmantree a = tree.poll();
            huffmantree b = tree.poll();
            
            tree.offer(new huffmannode(a, b));
        }
        return tree.poll();
        
    /**
     *
     * @param tree
     * @param prefix
     */
    }
    
    public void printhuffman(huffmantree tree, StringBuffer prefix){
        assert tree != null;
        if(tree instanceof huffmanleaf){
            huffmanleaf leaf = (huffmanleaf) tree;
            
            String xd = Character.toString(leaf.value) + "\t" + Integer.toString(leaf.frequency) + "\t" +  prefix.toString();
            out_huffman.append("\n" + xd);
            
        }else if(tree instanceof huffmannode){
            huffmannode node = (huffmannode) tree;
            
            prefix.append("0");
            printhuffman(node.left, prefix);
            prefix.deleteCharAt(prefix.length() - 1);
            
            prefix.append("1");
            printhuffman(node.right, prefix);
            prefix.deleteCharAt(prefix.length() - 1);
            
        }
    }
    
    private void clear_huffmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_huffmanActionPerformed
        // TODO add your handling code here:
        inp_huffman.setText("");
        out_huffman.setText("");
    }//GEN-LAST:event_clear_huffmanActionPerformed

    //METHODE SHANNONFANO
    private void btn_shanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shanoActionPerformed
        // TODO add your handling code here:
        String text = inp_shano.getText();
        counter c = new counter(text);

        out_shano.setText(c.toString());
    }//GEN-LAST:event_btn_shanoActionPerformed

    //METHOED RLE
    private String encode(String source){
        StringBuffer dest = new StringBuffer();
        for (int i = 0; i < source.length(); i++){
            int runLength = 1;
            while (i+1 < source.length() && source.charAt(i) == source.charAt(i+1)){
                runLength++;
                i++;
            }
            
            dest.append(source.charAt(i));
            dest.append("=");
            dest.append(runLength);
            dest.append("\n");
        }
        return dest.toString();   
    }
    
    /***
     * @param evt 
     */
    private void btn_rleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rleActionPerformed
        // TODO add your handling code here:
        String kata = inp_rle.getText();
        out_rle.setText(encode(kata));
    }//GEN-LAST:event_btn_rleActionPerformed

    
    //METHODE DICTIONARY
    
    static ArrayList<String> table = new ArrayList<>();
    static ArrayList<Integer> code = new ArrayList<>();
       
    private static void encoding(char[] s) 
	{
		/* Initialize Starting Table */
		table.add(Character.toString(s[0]));
		
		for(int i=1; i<s.length; i++)
		{
			String toBeCompared = Character.toString(s[i]);
			if( !table.contains(toBeCompared)) table.add(toBeCompared); 
		}
		
		/* ENCODING */
		int i=0;
		while(i<s.length)
		{
			StringBuilder sb = new StringBuilder();
			if(i+1<s.length)
			{
				// Add new letter to the current letter
				sb.append(charToStr(s[i])).append(charToStr(s[++i]));
				
				/*
				 *	If the new combination is not in the table:
				 * 	1) Code the new combination of letters
				 * 	2) Add the new combination of letters to the table
				*/
				if( !table.contains(sb.toString())) 
				{
					code.add(table.indexOf(charToStr(s[i-1]))+1);
					table.add(sb.toString());
				}
				/*
				 * If the combination ( sb ) exists in the table:
				 * 	- Add new letter to the combination
				 * 	- Continue checking if the combination exists
				 * 	until you find new combination or you get to the end
				 */
				else
				{
					String temp = "";
					while(table.contains(sb.toString()))
					{
						temp = sb.toString();
						i++;
						if(i<s.length)sb.append(charToStr(s[i]));
						else break;
					}
					
					code.add(table.indexOf(temp)+1);
					if( !table.contains(sb.toString()))
					{
						table.add(sb.toString());
					}
							
				}
				
			}
			else break;
			
		}
		/* ENCODING END */
	}

	/* Convert char to String */
	private static String charToStr(char c)
	{
		return Character.toString(c);
	}
    
    
    private void btn_dictiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dictiActionPerformed
        // TODO add your handling code here:
        String kalimat = this.inp_dicti.getText();
	char[] sequence = kalimat.toCharArray();
		
	encoding(sequence);
				
	out_dicti.setText("Table: ");
	for(String s : table) out_dicti.append(table.indexOf(s)+1 + ": " + s);
		
	out_dicti.append("\nEncoded sequnce: ");
	for(Integer c : code) out_dicti.append(c+" ");

	/* Calculating compression percent */
	double ratio = ((double)sequence.length - (double)code.size())/(double)sequence.length;
	out_dicti.append("\n" + "Compression : " + (float)ratio*100 + " %");
    }//GEN-LAST:event_btn_dictiActionPerformed

    
    // METHODE BWT
    
        class FastScanner {
        StringTokenizer tok = new StringTokenizer("");
        BufferedReader in;

        FastScanner() {
            in = new BufferedReader(new InputStreamReader(System.in));
        }

        String next() throws IOException {
            while (!tok.hasMoreElements())
                tok = new StringTokenizer(in.readLine());
            return tok.nextToken();
        }

        int nextInt() throws IOException {
            return Integer.parseInt(next());
        }
    }

    String BWT(String text) {
        StringBuilder result = new StringBuilder();
        ArrayList<String> cycRot = new ArrayList<>();
        String rot = text;
        int lastCharIndex = rot.length()-1;
        for(int i=0;i<=lastCharIndex;i++){
            cycRot.add(rot);
            rot = rot.charAt(lastCharIndex) + rot.substring(0,lastCharIndex);
        }
        Collections.sort(cycRot);
        for(int i=0;i<cycRot.size();i++){
            result.append(cycRot.get(i).charAt(lastCharIndex));
        }
        // write your code here

        return result.toString();
    }
    private void btn_bwtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bwtActionPerformed
        // TODO add your handling code here:
        FastScanner scanner = new FastScanner();
        String karakter = inp_bwt.getText();
        out_bwt.setText(BWT(karakter));
    }//GEN-LAST:event_btn_bwtActionPerformed

    private void btn_huffmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huffmanActionPerformed
        // TODO add your handling code here:
        
        String kalimat = inp_huffman.getText();
        int[] charFreqs = new int[256];
        
        for(char c : kalimat.toCharArray()){
            charFreqs[c] = charFreqs[c] + 1;
        }
        
        huffmantree tree = builTree(charFreqs);
        
        out_huffman.setText("SYMBOL ||  WEIGHT  ||  HUFFMAN CODE");
        printhuffman(tree, new StringBuffer());
        
    }//GEN-LAST:event_btn_huffmanActionPerformed

    private void clear_rleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_rleActionPerformed
        // TODO add your handling code here:
        inp_rle.setText("");
        out_rle.setText("");
    }//GEN-LAST:event_clear_rleActionPerformed

    private void clear_dictiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_dictiActionPerformed
        // TODO add your handling code here:
        
        inp_dicti.setText("");
        out_dicti.setText("");
    }//GEN-LAST:event_clear_dictiActionPerformed

    private void clear_shanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_shanoActionPerformed
        // TODO add your handling code here:
        inp_shano.setText("");
        out_shano.setText("");
        
    }//GEN-LAST:event_clear_shanoActionPerformed

    private void clear_bwtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_bwtActionPerformed
        // TODO add your handling code here:
        inp_bwt.setText("");
        out_bwt.setText("");
    }//GEN-LAST:event_clear_bwtActionPerformed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_headerMouseDragged

       int xx,xy;
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    

                         
          
    
    
    

        
    /**
     * @param args the command line arguments
     */
    
    
    
     
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,34,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_2;
    private javax.swing.JPanel btn_3;
    private javax.swing.JPanel btn_4;
    private javax.swing.JPanel btn_5;
    private javax.swing.JPanel btn_6;
    private java.awt.Button btn_bwt;
    private java.awt.Button btn_dicti;
    private java.awt.Button btn_huffman;
    private java.awt.Button btn_rle;
    private java.awt.Button btn_shano;
    private javax.swing.JPanel bwt;
    private java.awt.Button clear_bwt;
    private java.awt.Button clear_dicti;
    private java.awt.Button clear_huffman;
    private java.awt.Button clear_rle;
    private java.awt.Button clear_shano;
    private javax.swing.JPanel dicti;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JPanel huffman;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JPanel ind_6;
    private javax.swing.JTextArea inp_bwt;
    private javax.swing.JTextArea inp_dicti;
    private javax.swing.JTextArea inp_huffman;
    private javax.swing.JTextArea inp_rle;
    private javax.swing.JTextArea inp_shano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel main;
    private javax.swing.JTextArea out_bwt;
    private javax.swing.JTextArea out_dicti;
    private javax.swing.JTextArea out_huffman;
    private javax.swing.JTextArea out_rle;
    private javax.swing.JTextArea out_shano;
    private javax.swing.JPanel rle;
    private javax.swing.JPanel shano;
    private javax.swing.JPanel sider;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables
}
